### ISSUE TITLE
Document locked

### ISSUE THREAD

**Issue by iwkse** [cetra3/onlyoffice-alfresco#7]
Hi,
could be possible to change the lock message to something like "the document is being edited by user" + userName?

The actual text is not exactly right. I know it's the default lock message, but maybe there's a way to override it from the integration. That would be make it more user friendly.

Glad to know your opinion on that

Regards

**Comment by cetra3** [comment]
Yep, this is possible. Just need to update the banner config to override the generic locked message.

**Comment by iwkse** [comment]
But this would also affect the generic lock message? I mean, it would be right if it worked only in the OnlyOffice context and not in all locks.

**Comment by cetra3** [comment]
@iwkse I've pushed the newest version which has this change.  

The lock banner will read:

```
<user> is editing this document in ONLYOFFICE, join them by clicking here.
```

Where <user> is the current user, and `here` is a link to the edit document.

**Comment by tamim74** [comment]
Hi @cetra3 
I am still getting message like "This document is locked by <Username>". But the option to edit in onlyoffice is still there.
Do I need to change any config so that I get banner like "user> is editing this document in ONLYOFFICE, join them by clicking here."
